name: pytl_backup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^8.2.2
  provider: ^6.1.5+1
  http: ^1.6.0
  image_picker: ^1.2.1
  file_picker: ^10.3.6
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: 'assets/ico.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
